parameters:
#    bloggy_blog.example.class: Bloggy\Bundle\BlogBundle\Example

services:
#    bloggy_blog.example:
#        class: %bloggy_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
